### ISSUE TITLE
against discord Terms of service 

### ISSUE THREAD

**Issue by oriapp** [WaterTheDev/Vibez-Discord-Selfbot#7]
Just letting the creator and this program users know, that this is against discord ToS and can cause you're account in getting banned from Discord

**Comment by oriapp** [comment]
And yes @WaterTheDev I saw what you wrote at line 227-228, but still why would you publish such a thing?

**Comment by slab0x0** [comment]
imagine following tos

**Comment by oriapp** [comment]
imaging not 🙄

**Comment by slab0x0** [comment]
i can tell that you're a furry and a discord mod

**Comment by slab0x0** [comment]
kys lmao
.

**Comment by dromzeh** [comment]
> 
> 
> Just letting the creator and this program users know, that this is against discord ToS and can cause you're account in getting banned from Discord

it's obvious it's against tos but the chances of discord doing anything is low, just don't be stupid using the program and don't blatantly show people ur self botting and you will most likely be fine

**Comment by oriapp** [comment]
> > 
> > 
> > Just letting the creator and this program users know, that this is against discord ToS and can cause you're account in getting banned from Discord
> 
> it's obvious it's against tos but the chances of discord doing anything is low, just don't be stupid using the program and don't blatantly show people ur self botting and you will most likely be fine

well, if someone will report this to Discord, I'm 99.9% sure that they will take actions and warn / disable the user account. why taking any risk for this and braking the ToS of Discord?

**Comment by dromzeh** [comment]
> 
> 
> > > Just letting the creator and this program users know, that this is against discord ToS and can cause you're account in getting banned from Discord
> > 
> > 
> > it's obvious it's against tos but the chances of discord doing anything is low, just don't be stupid using the program and don't blatantly show people ur self botting and you will most likely be fine
> 
> well, if someone will report this to Discord, I'm 99.9% sure that they will take actions and warn / disable the user account. why taking any risk for this and braking the ToS of Discord?

i've seen loads of people self botting in the past, they've been reported, and their accounts are still up right now, since a fair amount of people do tos violation stuff like this (not even counting the amount of people who have been reported for using betterdiscord / powercord, considered against tos for modifiying the client) 

it's probably hard for discord to keep up with all the reports they recieve for these type of tos violations + people can do as they wish and it does state in the program it is against tos, so it's mainly the self-botter's fault if they get banned for blatantly self-botting infront of others; discord can only have proof of self-botters from message links, ids, etc (screenshots etc do not count as, ofc, they can be easily edited)

however, when a message gets deleted discord's servers no longer store that message link, message id etc, so the self-botter can easily just delete the message id and then there's pretty much hardly any proof left for discord to obtain about someone self-botting to get their account deleted, warned, disabled etc.

in reality, it's more of a "don't be stupid using the program and you will be fine" situation, but your issue / concern about breaking tos is completely reasonable 😄

**Comment by oriapp** [comment]
@dromzeh It's true they have thousands of tickets to take handle of, and sometime even missing stuff. but once you send a good report with all the information needed and everything related to the case most of the time they will actually take care of it. after it, users come to discord with new accounts and literally spamming then and asking why i got banned for doing "nothing". those kids are mostly skidz(s), and when someone like @WaterTheDev is coming here and uploading  those kind of things to skidz It's not ok.

**Comment by WaterTheDev** [comment]
urm u should already know the punishments of using a selfbot if u read the ToS and if u didn't read tos u should not be on discord.
